### PR TITLE
Handle elements conflict gracefully

### LINKED ISSUE #522: Repeated error in RDS logs
## In what situation are you experiencing subpar performance?

Our RDS logs are getting hammered by the same message every few seconds, not sure if this is a bug, or peformance related, but we're churning through logs and our metrics don't look great.

```
2021-07-30 11:00:06 UTC:10.0.10.6(54102):[9249]:ERROR: duplicate key value violates unique constraint "unique hash for each team"
2021-07-30 11:00:06 UTC:10.0.10.6(54102):[9249]:DETAIL: Key (team_id, hash)=(1, <HASH>) already exists.
2021-07-30 11:00:06 UTC:10.0.10.6(54102) [9249]:STATEMENT: INSERT INTO posthog_elementgroup (hash, team_id) VALUES ($1, $2) RETURNING *
```

## How to reproduce

1. Fire up a self hosted PostHog in AWS, on 1.27.0?

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog, version/commit: 1.27.0

## Additional context

N/A

### PR DESCRIPTION
**Pull request by yakkomajuri**
## Changes

Fixes #522 

Prevents us from erroring (and thus log spamming) on a pretty natural and harmless race condition where we try to insert the same elements twice.

## Checklist

-   [ ] Updated Settings section in README.md, if settings are affected
-   [ ] Jest tests

### CODE REVIEW

File: src/utils/db/db.ts [hunk 1]
```diff
@@ -745,27 +745,30 @@ export class DB {
...
+                                element.nth_child,
+                                element.nth_of_type,
+                                element.attributes || '{}',
+                                element.order,
+                                element.event_id,
+                                element.attr_class,
+                                elementGroup.id,
+                            ]
+                        )
+                    }
```
Comment (Twixes) [inline src/utils/db/db.ts:771]: BTW this looks like a good opportunity for replacing multiple insertions (slowed down by `await`) with a single `INSERT INTO foo (a, b) VALUES ($1, $2), ($3, $4), ...`

**Review by Twixes — APPROVED** [review]
This looks good

File: src/utils/db/db.ts (hunk 1 above)
Comment (yakkomajuri) [reply src/utils/db/db.ts:771]: I'll get this in and do another PR just so I'm conceptually getting through my to-do list as it pertains to race conditions and all
